config/routes.rb
Rails.application.routes.draw do
  get 'user/index'

  resources :users

  root 'users#index'

  post 'users/import'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :relationship_type
	belongs_to :user
	belongs_to :related_user, :class_name => 'User'
end

app/models/relationship_type.rb
class RelationshipType < ApplicationRecord
	has_many :relationships
	has_many :users, through: :relationships

	scope :grandfather, -> { where(name: 'grandfather') }
	scope :father, -> { where(name: 'father') }
end

app/models/user.rb
class User < ApplicationRecord

	require 'csv'
	require 'activerecord-import/base'

	has_many :relationships
	has_many :reverse_relationships, class_name: 'Relationship', foreign_key: 'related_user_id'

	GRAND_FATHER = RelationshipType.find_or_create_by(name: 'grandfather', reverse_name: 'grandson')
	FATHER = RelationshipType.find_or_create_by(name: 'father', reverse_name: 'son')

	def self.my_import(file)
		users = []
		CSV.foreach(file.path, headers: true) do |row|
			User.create_three_generations(row.to_h)
		end
	end

	# TODO: MOVE TO BACKGROUND JOB

	def self.create_three_generations(row_hash) 
		grand_father = User.find_or_create_by(name: row_hash["Grand Father"])
		father = User.find_or_create_by(name: row_hash["Father"])
		son = User.find_or_create_by(name: row_hash["Son"])

		grand_father.relate(father, FATHER)
		father.relate(son, FATHER)
		grand_father.relate(son, GRAND_FATHER)

		# Assumption: Grand Father lives with youngest grandson
		grand_father.address = father.address = son.address = row_hash["Address"]

		# TODO: REFACTOR
		grand_father.save
		father.save
		son.save
	end

	def relate(related_user, relationship_type)
	  self.relationships.find_or_create_by!(relationship_type_id: relationship_type.id, related_user_id: related_user.id)
	end

	def sons
		sons_relationships = relationships.where(relationship_type_id: FATHER.id, user_id: id)
		User.where(id: sons_relationships.pluck(:related_user_id))
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		grandfather_relation = RelationshipType.grandfather.last
		@grandfathers = grandfather_relation.users.uniq
	end

	def import
		User.my_import(params[:file])
		redirect_to root_url, notice: "Success"
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThreeGeneration</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h1>Users controller</h1>

<%= flash[:notice] %>
<div>
	<h4>Import data!</h4>
	<%= form_tag users_import_path, multipart: true do %>
		<%= file_field_tag :file %>
		<%= submit_tag "Import from file" %>
	<% end %>
</div>
<% @grandfathers.each do |grandfather| %>
	<ul>
		<li><%= grandfather.name%></li>				
		<% grandfather.sons.each do |father| %>
			<ul>
				<li><%= father.name%></li>
				<% father.sons.each do |son| %>		
					<ul>
						<li><%= son.name%></li>
					</ul>
				<% end %>
			</ul>
		<% end %>
	</ul>
<% end %>